name: AutoDownloader
on:
  #workflow_dispatch: # 手动触发
  gollum
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 2
        keep_minimum_runs: 6
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Aria2 Install(无限制版本)
      run: |
        wget https://github.com/P3TERX/Aria2-Pro-Core/releases/download/1.36.0_2021.08.22/aria2-1.36.0-static-linux-amd64.tar.gz
        tar zxvf aria2-1.36.0-static-linux-amd64.tar.gz
        sudo mv aria2c /usr/local/bin
    - name: 确定 Rclone&Aria2 config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
    - name: 添加Tracker
      run: |
        cd ~/.aria2
        wget git.io/tracker.sh
        chmod 0777 ~/.aria2/tracker.sh
        /bin/bash ~/.aria2/tracker.sh
        cd ~/
    - name: Aria2_Downloading_File
      run: |
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd $wiki
        mdfile=`git log --pretty=format: -1 --name-only *.md`
        cd ..
        aria2c --seed-time=0 -d downloads `cat $wiki/$mdfile | xargs`
        echo "${mdfile:0:-3}:" > DEST
    - name: Rclone Synchronizing file
      run: |
        rclone copy downloads `cat DEST`
